"""
Reemplaza la función generatePromptForNiche en el index.html
por una versión robusta que usa array.join en vez de template literals anidados.
"""
import re

FILE = '/home/z/my-project/makeseo-mml-comunidad/public/index.html'

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

# Patrón: desde "    function generatePromptForNiche(niche) {" hasta el cierre del template literal "`;" 
# seguido de la asignación generatedPromptText = promptText;
# Usamos un patrón que captura toda la función vieja

# La función vieja empieza en "    function generatePromptForNiche(niche) {"
# y termina en "`;\n\n      generatedPromptText = promptText;"

start_marker = "    function generatePromptForNiche(niche) {"
end_marker = "      generatedPromptText = promptText;"

start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print("ERROR: No se encontraron los marcadores")
    exit(1)

# El final del bloque a reemplazar es después de "generatedPromptText = promptText;"
end_idx_full = end_idx + len(end_marker)

old_block = content[start_idx:end_idx_full]
print(f"Bloque viejo: {len(old_block)} chars, {old_block.count(chr(10))} líneas")

# Nueva función robusta usando array.join
new_function = '''    function generatePromptForNiche(niche) {
      // Slug del nicho en mayúsculas para el nombre del archivo
      var nicheSlug = niche.label.toUpperCase().replace(/[^A-Z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
      var nicheLower = niche.label.toLowerCase();
      var servicios = niche.servicios.map(function(s, i) { return (i + 1) + '. **' + s + '**'; }).join('\\n');
      var keywordsFirst = niche.keywords.split(',')[0].trim();

      // Construir el prompt con array.join (sin template literals anidados)
      var lines = [
        '# MASTER PROMPT — Landing SEO Local para ' + niche.label,
        '',
        '> Versión personalizada del Master Prompt MML generado automáticamente para el nicho **' + niche.label + '**. Pégalo completo en un nuevo chat con tu IA para construir una landing optimizada para SEO Local.',
        '',
        '---',
        '',
        '## 1. ROL Y OBJETIVO',
        '',
        'Actúa como **Desarrollador Web Full Stack Senior + Especialista en SEO Local y CRO**, experto en **Astro, Tailwind CSS, Git/GitHub y Cloudflare Pages**.',
        '',
        '**Objetivo:** Construir una landing page de servicios de **' + nicheLower + '** a domicilio, lista para producción, optimizada para:',
        '- Conversión móvil',
        '- Core Web Vitals (95+ en PageSpeed mobile)',
        '- SEO Local / Geo-SEO (city-level landing pages)',
        '- Rich snippets via Schema.org JSON-LD',
        '',
        '**Metodología:** Método Malla Local (MML) — sistema creado por Edward Valencia (@makeseo) para posicionar negocios en Google Maps, construir webs ultrarrápidas serverless con $0 hosting, y desplegar mallas territoriales de landings por comuna/municipio.',
        '',
        '---',
        '',
        '## 2. STACK TÉCNICO OBLIGATORIO',
        '',
        '| Capa | Tecnología | Razón |',
        '|------|------------|-------|',
        '| Framework | **Astro 4.x** (SSG / static output) | HTML estático = máxima velocidad |',
        '| Estilos | **Tailwind CSS 3.x** con tokens custom | Design system consistente |',
        '| Interactividad | **Vanilla JS** en `<script>` (sin React/Vue) | Mínimo JS = mejor INP |',
        '| Mapas | **Leaflet 1.9.4** + tiles OpenStreetMap con filtro CSS | Ver sección 11 |',
        '| Imágenes | **Sharp** (Node) para optimizar a WebP + JPG | ~50% de ahorro de peso |',
        '| Hosting | **Cloudflare Pages** | CDN global gratis, $0 hosting |',
        '',
        '**Prohibido:** React, Vue, Svelte, jQuery, Bootstrap, frameworks CSS pesados, WordPress.',
        '',
        '---',
        '',
        '## 3. SISTEMA DE DISEÑO — TOKENS TAILWIND (Dark Tech)',
        '',
        '```js',
        'colors: {',
        "  'primary-cyan':       '#00BCD4',",
        "  'primary-teal':       '#00838F',",
        "  'accent-orange':      '#ff6b00',",
        "  'accent-orange-light':'#ff8c33',",
        "  'dark-navy':          '#0b1020',",
        "  'dark-navy-alt':      '#121a33',",
        "  'whatsapp-green':     '#25D366',",
        '},',
        "fontFamily: { sans: ['Inter', 'Poppins', 'sans-serif'] }",
        '```',
        '',
        '**Fuentes:** Inter + Poppins desde Google Fonts con `preconnect` + `display=swap`.',
        '',
        '---',
        '',
        '## 4. ARQUITECTURA DE CARPETAS',
        '',
        '```',
        'proyecto/',
        '├── astro.config.mjs          # SSG, site URL, @astrojs/tailwind',
        '├── tailwind.config.mjs       # Tokens + animaciones',
        '├── public/',
        '│   ├── favicon.svg',
        '│   ├── robots.txt            # Con Sitemap',
        '│   ├── manifest.webmanifest  # PWA',
        '│   └── images/',
        '│       ├── logo.svg',
        '│       ├── og/               # Open Graph 1200×630',
        '│       ├── icons/            # icon-192.png, icon-512.png, apple-touch-icon.png',
        '│       ├── gallery/          # Fotos renombradas con keywords SEO',
        '│       └── services/         # Fotos por servicio',
        '└── src/',
        '    ├── data/',
        '    │   └── ubicaciones.ts    # Data centralizada (slug, nombre, zona, lat/lng, FAQ)',
        '    ├── layouts/',
        '    │   └── Layout.astro      # Head + SEO + Geo-tags + Schema JSON-LD',
        '    ├── components/',
        '    │   ├── Navbar.astro',
        '    │   ├── Hero.astro',
        '    │   ├── TrustBar.astro',
        '    │   ├── ServicesGrid.astro',
        '    │   ├── ProcessSteps.astro',
        '    │   ├── PricingSection.astro',
        '    │   ├── CoverageMap.astro',
        '    │   ├── LeafletMap.astro',
        '    │   ├── Gallery.astro',
        '    │   ├── FaqSection.astro',
        '    │   ├── FloatingActions.astro',
        '    │   └── Footer.astro',
        '    └── pages/',
        '        ├── index.astro              # Home',
        '        ├── ubicaciones.astro        # Hub + mapa amplio',
        '        ├── ubicacion/[slug].astro   # N landings dinámicas',
        '        ├── faq.astro                # FAQ global',
        '        ├── galeria.astro            # Galería completa',
        '        ├── privacidad.astro         # Política de privacidad',
        '        └── sitemap.xml.ts           # Sitemap dinámico',
        '```',
        '',
        '---',
        '',
        '## 5. SERVICIOS DEL NICHO ' + niche.label.toUpperCase() + ' (SERVICESGRID)',
        '',
        'Configurar las tarjetas de servicios con EXACTAMENTE estos servicios típicos del nicho:',
        '',
        servicios,
        '',
        'Cada servicio debe tener:',
        '- Imagen optimizada (WebP + JPG, `loading="lazy"`, `width`+`height` explícitos)',
        '- Título con keyword + ubicación',
        '- Descripción persuasiva de 2-3 líneas',
        '- Lista de inclusiones (4-5 items)',
        '- Precio en moneda local',
        '- Botón CTA WhatsApp con mensaje pre-rellenado mencionando el servicio',
        '',
        '---',
        '',
        '## 6. PÁGINA DINÁMICA POR UBICACIÓN — `[slug].astro`',
        '',
        'Generar una landing SEO por cada comuna/municipio/barrio que el negocio cubre.',
        '',
        '### Data source: `src/data/ubicaciones.ts`',
        '```ts',
        'export interface Ubicacion {',
        "  slug: string;",
        "  nombre: string;",
        "  zona: 'Centro'|'Oriente'|'Norte'|'Sur'|'Oeste'|'Rural';",
        "  descripcion: string;",
        "  barrios?: string[];",
        "  lat: number;",
        "  lng: number;",
        "  tiempoRespuesta: string;",
        "  faqs: UbicacionFAQ[];",
        '}',
        '```',
        '',
        '### `getStaticPaths()`',
        '```astro',
        'export function getStaticPaths() {',
        '  return ubicaciones.map((ubi) => ({',
        '    params: { slug: ubi.slug },',
        '    props: { ubi },',
        '  }));',
        '}',
        '```',
        '',
        '### Estructura de cada landing por ubicación',
        '- **Hero específico:** H1 con "' + niche.servicios[0] + ' a Domicilio en {ubicacion.nombre}"',
        '- Breadcrumb: Inicio › Cobertura › {ubicacion.nombre}',
        '- Badge: "Desde $X · Atención hoy en {ubicacion.nombre}"',
        '- Barrios atendidos como chips',
        '- CTA WhatsApp con mensaje pre-rellenado mencionando la ubicación',
        '- TrustBar + ServicesGrid + ProcessSteps + PricingSection (componentes compartidos)',
        '- **FAQ específico de la ubicación** (5 preguntas con nombre de la ubicación)',
        '- Gallery compacta',
        '- **Ubicaciones vecinas** como chips clickeables',
        '',
        '### Schemas por ubicación (4 en total)',
        '1. `' + niche.schema + '` (LocalBusiness subtipo) con `areaServed` = City + `geo` con lat/lng específicos',
        '2. `Service` con `areaServed` = City + `Offer` en moneda local',
        '3. `FAQPage` con 5 FAQs únicas',
        '4. `BreadcrumbList` con Inicio › Cobertura › {ubicacion}',
        '',
        '---',
        '',
        '## 7. SCHEMA.ORG JSON-LD — PATRONES',
        '',
        '### 7.1 ' + niche.schema + ' (en Layout principal)',
        '```json',
        '{',
        '  "@context": "https://schema.org",',
        '  "@type": ["LocalBusiness", "' + niche.schema + '"],',
        '  "@id": "https://dominio.com/#business",',
        '  "name": "Nombre del negocio de ' + nicheLower + '",',
        '  "telephone": "+XX-XXXX-XXXX",',
        '  "image": ".../og-image.jpg",',
        '  "logo": ".../logo.svg",',
        '  "priceRange": "$$",',
        '  "currenciesAccepted": "USD",',
        '  "paymentAccepted": "Efectivo, Transferencia, Tarjeta",',
        '  "address": { "@type": "PostalAddress", "addressLocality": "Ciudad", "addressRegion": "Región", "addressCountry": "XX" },',
        '  "geo": { "@type": "GeoCoordinates", "latitude": 0, "longitude": 0 },',
        '  "areaServed": [ /* array de { "@type": "City", "name": "..." } */ ],',
        '  "openingHoursSpecification": [',
        '    { "@type": "OpeningHoursSpecification", "dayOfWeek": ["Monday","Tuesday","Wednesday","Thursday","Friday"], "opens": "08:00", "closes": "22:00" },',
        '    { "@type": "OpeningHoursSpecification", "dayOfWeek": ["Saturday","Sunday"], "opens": "09:00", "closes": "21:00" }',
        '  ],',
        '  "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.9", "reviewCount": "327" }',
        '}',
        '```',
        '',
        '### 7.2 Service',
        '```json',
        '{',
        '  "@context": "https://schema.org",',
        '  "@type": "Service",',
        '  "serviceType": "' + niche.servicios[0] + '",',
        '  "provider": { "@id": ".../#business" },',
        '  "areaServed": { "@type": "AdministrativeArea", "name": "Región" },',
        '  "offers": { "@type": "Offer", "price": "X", "priceCurrency": "USD", "availability": "InStock" }',
        '}',
        '```',
        '',
        '### 7.3 FAQPage',
        '```json',
        '{',
        '  "@context": "https://schema.org",',
        '  "@type": "FAQPage",',
        '  "mainEntity": [',
        '    { "@type": "Question", "name": "...", "acceptedAnswer": { "@type": "Answer", "text": "..." } }',
        '  ]',
        '}',
        '```',
        '',
        '---',
        '',
        '## 8. SEO ON-PAGE CHECKLIST',
        '',
        '- [ ] Un único `<h1>` con keyword transaccional: "' + niche.servicios[0] + ' a Domicilio en {Ciudad}"',
        '- [ ] `<title>` 50–60 chars: "' + niche.servicios[0] + ' a Domicilio en {Ciudad} | {Marca}"',
        '- [ ] `<meta description>` 150–160 chars con precio + tiempo + CTA',
        '- [ ] Geo-tags: `geo.region`, `geo.placename`, `geo.position`, `ICBM`',
        '- [ ] Open Graph completo con `og:locale`',
        '- [ ] Twitter Cards `summary_large_image`',
        '- [ ] `<link rel="canonical">`',
        '- [ ] `robots.txt` con `Sitemap: https://dominio.com/sitemap.xml`',
        '- [ ] `sitemap.xml` dinámico con todas las URLs',
        '- [ ] Imágenes: `alt` descriptivo con keywords (' + niche.keywords + '), `width`+`height`, `loading="lazy"`',
        '- [ ] `prefers-reduced-motion` respetado',
        '- [ ] `lang="es-XX"` en `<html>`',
        '',
        '### Keywords principales del nicho ' + niche.label + ':',
        niche.keywords,
        '',
        '---',
        '',
        '## 9. PWA — WEB MANIFEST',
        '',
        '```json',
        '{',
        '  "name": "Negocio de ' + niche.label + ' - Servicio a Domicilio",',
        '  "short_name": "' + niche.label + '",',
        '  "description": "Servicio de ' + nicheLower + ' a domicilio en tu ciudad.",',
        '  "start_url": "/",',
        '  "display": "standalone",',
        '  "background_color": "#0b1020",',
        '  "theme_color": "#00838F",',
        '  "icons": [',
        '    { "src": "/favicon.svg", "sizes": "any", "type": "image/svg+xml", "purpose": "any maskable" },',
        '    { "src": "/images/icons/icon-192.png", "sizes": "192x192", "type": "image/png" },',
        '    { "src": "/images/icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable" }',
        '  ]',
        '}',
        '```',
        '',
        'Generar iconos PNG con sharp desde el favicon.svg (densidad 384, tamaños 192/512/180).',
        '',
        '---',
        '',
        '## 10. IMÁGENES — CONVENCIONES',
        '',
        '### Renombrado SEO (kebab-case con keywords del nicho ' + nicheLower + ')',
        '- ✅ `' + niche.id + '-a-domicilio-en-ciudad-1.jpg`',
        '- ✅ `tecnico-' + niche.id + '-profesional-domicilio-3.webp`',
        '- ❌ `IMG-20260929-WA0132.jpg`',
        '',
        '### Optimización con sharp',
        '```js',
        'await sharp(input).resize({ width: 1200, height: 1200, fit: "inside", withoutEnlargement: true })',
        '  .jpeg({ quality: 78, progressive: true, mozjpeg: true }).toBuffer();',
        'await sharp(input).resize({...}).webp({ quality: 75 }).toFile(output);',
        '```',
        '',
        '### Uso en HTML',
        '```html',
        '<picture>',
        '  <source srcset="/images/gallery/foto.webp" type="image/webp" />',
        '  <img src="/images/gallery/foto.jpg" alt="' + keywordsFirst + ' en {Ciudad}"',
        '       width="900" height="1200" loading="lazy" decoding="async" />',
        '</picture>',
        '```',
        '',
        '**Excepción:** Hero principal usa `fetchpriority="high"` (no lazy).',
        '',
        '---',
        '',
        '## 11. MAPA INTERACTIVO — LECCIONES CRÍTICAS',
        '',
        '### ❌ NO USES SVG CUSTOM',
        'SVG con 50+ markers animados + transforms JS = lag severo en mobile.',
        '',
        '### ❌ NO USES CARTODB TILES',
        'Requiere API key ahora. Muestra "API KEY REQUIRED" tapando el mapa.',
        '',
        '### ✅ SOLUCIÓN: Leaflet + OpenStreetMap + Filtro CSS',
        '',
        '```js',
        'L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {',
        '  attribution: "&copy; OpenStreetMap",',
        '  subdomains: "abc",',
        '  maxZoom: 19,',
        '  className: "osm-dark-tiles",',
        '}).addTo(map);',
        '```',
        '',
        '```css',
        '.osm-dark-tiles {',
        '  filter: invert(1) hue-rotate(180deg) brightness(0.85) contrast(0.9) saturate(0.7);',
        '}',
        '```',
        '',
        '### Carga vía CDN con SRI',
        '```html',
        '<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"',
        '      integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="',
        '      crossorigin="" />',
        '<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"',
        '        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="',
        '        crossorigin=""></script>',
        '```',
        '',
        '### Configuración',
        '```js',
        'var map = L.map("leaflet-map", {',
        '  center: [LAT, LNG],  // centro de tu zona',
        '  zoom: 10,',
        '  minZoom: 9,',
        '  maxZoom: 16,',
        '  zoomControl: true,',
        '  scrollWheelZoom: true,',
        '});',
        '```',
        '',
        '---',
        '',
        '## 12. SITEMAP DINÁMICO',
        '',
        '```ts',
        'import type { APIRoute } from "astro";',
        'import { ubicaciones } from "../data/ubicaciones.ts";',
        '',
        'const SITE_URL = "https://dominio.com";',
        '',
        'export const GET: APIRoute = () => {',
        '  var pages = [',
        '    { url: "/", priority: "1.0", changefreq: "weekly" },',
        '    { url: "/faq", priority: "0.8", changefreq: "monthly" },',
        '    { url: "/galeria", priority: "0.7", changefreq: "monthly" },',
        '    { url: "/ubicaciones", priority: "0.9", changefreq: "monthly" },',
        '    { url: "/privacidad", priority: "0.3", changefreq: "yearly" },',
        '  ].concat(ubicaciones.map(function(u) { return { url: "/ubicacion/" + u.slug, priority: "0.9", changefreq: "monthly" }; }));',
        '  var xml = "<?xml version=\\\\\"1.0\\\\\" encoding=\\\\\"UTF-8\\\\\"?>\\n<urlset xmlns=\\\\\"http://www.sitemaps.org/schemas/sitemap/0.9\\\\\">\\n";',
        '  xml += pages.map(function(p) {',
        '    return "  <url>\\n    <loc>" + SITE_URL + p.url + "</loc>\\n    <lastmod>" + new Date().toISOString().split("T")[0] + "</lastmod>\\n    <changefreq>" + p.changefreq + "</changefreq>\\n    <priority>" + p.priority + "</priority>\\n  </url>";',
        '  }).join("\\n");',
        '  xml += "\\n</urlset>";',
        '  return new Response(xml, { headers: { "Content-Type": "application/xml; charset=utf-8" } });',
        '};',
        '```',
        '',
        '---',
        '',
        '## 13. WORKFLOW DE DESPLIEGUE',
        '',
        '### 13.1 Git init + commit',
        '```bash',
        'cd proyecto',
        'git init -b main',
        'git add .',
        'git commit -m "feat: landing ' + nicheLower + ' - MML"',
        '```',
        '',
        '### 13.2 GitHub',
        '```bash',
        'gh auth login',
        'gh repo create nombre-repo --private --source=. --push',
        '```',
        '',
        '### 13.3 Cloudflare Pages',
        '1. dash.cloudflare.com → Workers & Pages → Create → Pages → Connect to Git',
        '2. Seleccionar repo',
        '3. Config: Framework preset `Astro`, Build command `npm run build`, Build output `dist`',
        '4. Save and Deploy',
        '',
        'O vía Wrangler CLI:',
        '```bash',
        'npm install -g wrangler',
        'wrangler login',
        'wrangler pages project create nombre-proyecto',
        'npm run build',
        'wrangler pages deploy dist --project-name=nombre-proyecto --branch=main',
        '```',
        '',
        '---',
        '',
        '## 14. SEGURIDAD — REGLAS CRÍTICAS',
        '',
        '### ⚠️ NUNCA compartas tokens en chat',
        'Si el usuario pega tokens de GitHub (`ghp_...`) o Cloudflare (`cfat_...`):',
        '1. Advertir inmediatamente que los revoque',
        '2. No usar los tokens sin confirmación explícita',
        '3. Recomendar rotación en github.com/settings/tokens y dash.cloudflare.com/profile/api-tokens',
        '',
        '### `.gitignore` obligatorio',
        '```',
        'node_modules/',
        'dist/',
        '.env',
        '.env.local',
        '.env.production',
        '.astro/',
        '.DS_Store',
        '```',
        '',
        '---',
        '',
        '## 15. CALIDAD — CHECKLIST FINAL',
        '',
        '### Build',
        '- [ ] `npm run build` compila sin errores',
        '- [ ] Total de páginas = 1 home + N landings por ubicación + páginas auxiliares',
        '',
        '### SEO',
        '- [ ] Un único `<h1>` por página',
        '- [ ] Schemas JSON-LD válidos (probar en search.google.com/test/rich-results)',
        '- [ ] Sitemap accessible en `/sitemap.xml`',
        '- [ ] Geo-tags presentes',
        '- [ ] canonical URL correcta',
        '',
        '### Performance',
        '- [ ] Sin React/Vue/jQuery',
        '- [ ] Imágenes en WebP + JPG con `<picture>`',
        '- [ ] `loading="lazy"` en imágenes bajo el fold',
        '- [ ] `fetchpriority="high"` en imagen del Hero',
        '- [ ] `width`+`height` en todas las imágenes (evita CLS)',
        '- [ ] Fuentes con `preconnect` + `display=swap`',
        '',
        '### Accesibilidad',
        '- [ ] `lang="es-XX"` en `<html>`',
        '- [ ] `aria-label` en botones de iconos',
        '- [ ] `aria-expanded` en dropdowns y acordeones',
        '- [ ] `prefers-reduced-motion` respetado',
        '',
        '### PWA',
        '- [ ] `manifest.webmanifest` válido',
        '- [ ] Iconos 192, 512, apple-touch-icon 180',
        '',
        '### Mapa',
        '- [ ] Leaflet 1.9.4 vía CDN con SRI',
        '- [ ] Tiles OpenStreetMap (NO CartoDB)',
        '- [ ] Filtro CSS `invert(1) hue-rotate(180deg)` para dark theme',
        '',
        '---',
        '',
        '## 16. LECCIONES APRENDIDAS — ERRORES A EVITAR',
        '',
        '### 16.1 Foto del Hero como background',
        '❌ No uses foto como `background` absoluto del Hero con `object-cover` (zoom/recorte + mala legibilidad).',
        '✅ Patrón correcto: Hero sin foto de fondo (solo glow), texto directo sobre dark-navy, foto como `<figure>` bloque independiente debajo con `object-contain` y `max-h-[70vh]`.',
        '',
        '### 16.2 Tarjeta "Servicio Garantizado" en columna derecha del Hero',
        '❌ No la pongas como columna derecha del Hero (compite con foto de fondo).',
        '✅ Sección independiente debajo del Hero.',
        '',
        '### 16.3 SVG custom para mapas',
        '❌ No uses SVG con 50+ markers animados (lag severo).',
        '✅ Leaflet + tiles OSM rasterizados.',
        '',
        '### 16.4 CartoDB tiles',
        '❌ No uses `basemaps.cartocdn.com/dark_all` (requiere API key).',
        '✅ `tile.openstreetmap.org/{z}/{x}/{y}.png` + filtro CSS.',
        '',
        '### 16.5 Tokens en el chat',
        '❌ Nunca aceptes tokens pegados en el chat sin advertir al usuario que los revoque.',
        '',
        '### 16.6 Hard refresh',
        'Después de cada deploy, recordar al usuario hacer hard refresh:',
        '- Windows/Linux: `Ctrl + Shift + R`',
        '- Mac: `Cmd + Shift + R`',
        '',
        '---',
        '',
        '## 17. PROMPT INICIAL SUGERIDO',
        '',
        '```',
        'Actúa como Desarrollador Web Full Stack Senior + Especialista en SEO Local.',
        '',
        'Construye una landing page de ' + niche.label + ' a domicilio en [CIUDAD/REGIÓN] siguiendo',
        'EXACTAMENTE el master prompt adjunto (Método MML). Ciudad: [nombre].',
        'Comunas/sectores a cubrir: [N] ubicaciones.',
        '',
        'Stack: Astro 4 + Tailwind CSS + Vanilla JS + Leaflet + Cloudflare Pages.',
        '',
        'Entregar:',
        '1. Repo local con git init + commit inicial',
        '2. Build SSG que genere [N + 5] páginas',
        '3. SEO on-page completo con Schema.org JSON-LD (' + niche.schema + ' + Service + FAQPage + BreadcrumbList)',
        '4. Webmanifest PWA + iconos',
        '5. Sitemap dinámico',
        '6. Mapa Leaflet con tiles OSM + filtro CSS dark',
        '7. Galería con lightbox',
        '8. Deploy a GitHub + Cloudflare Pages',
        '```',
        '',
        '---',
        '',
        '## 18. ARCHIVOS DE REFERENCIA',
        '',
        '```',
        'Páginas HTML totales:',
        '├── /                          # Home',
        '├── /ubicaciones               # Hub + mapa amplio',
        '├── /ubicacion/[slug]          # N landings',
        '├── /faq                       # FAQ global',
        '├── /galeria                   # Galería completa',
        '├── /privacidad                # Política de privacidad',
        '└── /sitemap.xml               # Sitemap dinámico',
        '',
        'Componentes clave:',
        '├── Layout.astro              # Head + SEO + Schema',
        '├── Navbar.astro              # Sticky + mega-dropdown Ubicaciones',
        '├── Hero.astro                # Sin foto de fondo (solo glow)',
        '├── LeafletMap.astro          # Leaflet + OSM + filtro CSS',
        '├── Gallery.astro             # Lightbox accesible',
        '└── Footer.astro              # Datos fiscales + listado SEO ubicaciones',
        '',
        'Data:',
        '└── src/data/ubicaciones.ts   # N ubicaciones con slug, nombre, zona, lat/lng, FAQ único',
        '```',
        '',
        '---',
        '',
        '**Fin del Master Prompt MML para ' + niche.label + '.** Pega esto completo en un nuevo chat para construir tu landing SEO Local.',
        '',
        '*Método Malla Local (MML) · Edward Valencia · @makeseo · 360 Soluciones*'
      ];

      var promptText = lines.join('\\n');

      generatedPromptText = promptText;'''

content = content[:start_idx] + new_function + content[end_idx_full:]

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print("✓ Función reemplazada correctamente")
print(f"  Nuevo tamaño: {len(content)} chars")
print(f"  Nuevas líneas: {content.count(chr(10))}")
